admin/urls.py
from django.urls import path

from .views import AdminDashboardView, AdminDashboardChartData, AdminBlogListView, AdminBlogDeleteView, LoginView, \
    logout_view

app_name = 'admin'

urlpatterns = [
    path('', AdminDashboardView.as_view(), name='dashboard'),
    path('dashboard_data', AdminDashboardChartData.as_view(), name='dashboard-data'),
    path('blogs/', AdminBlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>/delete', AdminBlogDeleteView.as_view(), name='blog-delete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

blogs/urls.py
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register(r'categories', views.CategoryViews)
router.register(r'posts', views.PostViews)
router.register(r'blogs', views.BlogViews)

urlpatterns = router.urls

qtec_blog/urls.py
from django.conf.urls.static import static, settings
from django.urls import path, include

urlpatterns = [
    path('admin/', include("admin.urls")),
    path('accounts/', include("accounts.urls")),
    path('', include("blogs.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static("static/", document_root=settings.STATIC_ROOT)
urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

blogs/models.py
from PIL import Image
from django.db import models

from accounts.models import User


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=255)


class Blog(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='blogs')
    title = models.CharField(max_length=150)
    banner = models.ImageField()
    description = models.TextField()
    total_views = models.IntegerField(default=0)
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blogs')

    REQUIRED_FIELDS = ['category', 'title', 'banner', 'description']

    def save(self, *args, **kwargs):
        img = Image.open(self.banner)
        quality = 60  # 60% of original quality
        img.save(self.banner.path, quality=quality)

        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.title}'


class Post(models.Model):
    title = models.CharField(max_length=255)
    post_text = models.TextField()
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='posts')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')

blogs/views.py
# Create your views here.
from http import HTTPStatus

from rest_framework import permissions, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from silk.profiling.profiler import silk_profile

from utils.views import GetBaseModelViewSet
from .models import Category, Blog, Post
from .permissions import IsAuthor, ReadOnlyIfAuthenticated, IsOwnerOfPostBlog
from .serializers import CategorySerializer, BlogSerializer, PostSerializer
from .utils import autocorrect_string

BaseModelViewSet_category = GetBaseModelViewSet("category")
BaseModelViewSet_blog = GetBaseModelViewSet("blog")
BaseModelViewSet_post = GetBaseModelViewSet("post")


class CategoryViews(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAdminUser | ReadOnlyIfAuthenticated]


class BlogViews(BaseModelViewSet_blog):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [permissions.IsAdminUser | IsAuthor | ReadOnlyIfAuthenticated]

    @action(detail=False, methods=['GET'])
    @silk_profile(name='search_blogs')
    def search(self, request):
        # get search query param
        search_query = request.GET.get("q")
        if not search_query:
            return Response({
                "details": "Search query must be a string of length > 0"
            }, status=HTTPStatus.BAD_REQUEST)

        # autocorrect spelling
        corrected_query = autocorrect_string(search_query)

        # search the database on full text index
        results = Blog.objects.extra(
            where=[
                "MATCH(title, description) AGAINST (%s IN NATURAL LANGUAGE MODE)"],
            params=[corrected_query]
        )

        serialized = BlogSerializer(results, many=True, context={'request': request})
        return Response(serialized.data, status=HTTPStatus.OK)

    @action(detail=True, methods=['GET'])
    @silk_profile(name='get_posts_by_blog')
    def posts(self, request, pk=None):
        blog = self.get_object()
        posts = Post.objects.filter(blog=blog)

        serialized = PostSerializer(posts, many=True, context={'request': request})
        return Response(serialized.data, status=HTTPStatus.OK)


class PostViews(BaseModelViewSet_post):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAdminUser | IsOwnerOfPostBlog | ReadOnlyIfAuthenticated]

admin/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    <link rel="stylesheet" href="/static/output.css">

</head>


<body>
<div id="header" class="p-4">
    <!-- NAVIGATION BAR -->
    <nav id="navbar" class="flex justify-between text-xl text-white bg-black p-4 py-8 gap-4">
        <a class="text-white bg-black" href="#">ADMIN PANEL</a>
        <div class="text-xs text-slate-600">logged in as {{ user }}
            <a class="underline " href="{% url 'admin:logout' %}">logout</a>
        </div>
        <a class="text-white bg-black" href="{% url 'admin:blogs'%}">Blogs</a>
    </nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>

admin/templates/blog_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Blog</title>
</head>
<body>
<h1>Are you sure you want to delete "{{ object }}"?</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'admin:dashboard' %}">Cancel</a>
</form>
</body>
</html>

admin/templates/blogs.html
{% extends 'base.html' %}
{% block content %}

<script>
    function goPrev(){
        let params = new URLSearchParams(location.search);
        let prev_page = params.has("page") && params.get("page") > 1 ? params.get("page")-1 : 1;

        params.set('page', Number(prev_page));
        window.location.search = params.toString();
    }
    function goNext(){
        let params = new URLSearchParams(location.search);
        let current_page = params.has("page") ? params.get("page") : 1;

        params.set('page', Number(current_page)+1);
        window.location.search = params.toString();
    }


    function searchByAuthor(){
        let author = document.querySelector("#search_author").value;
        let params = new URLSearchParams(location.search);
        params.set('author', author);
        window.location.search = params.toString();
    }

    function searchByCategory(){
        let cat = document.querySelector("#search_category").value;
        let params = new URLSearchParams(location.search);
        params.set('category', cat);
        window.location.search = params.toString();
    }


</script>


<div class="h-full flex flex-col justify-center items-center gap-4 my-8">
    <div>
        <div>
            <label for="search_author" class="font-bold text-lg">Search by Author name : </label>
            <input id="search_author" class="border-b-[1px] p-2 px-6 border-slate-400 " type="text"
                   placeholder="John Doe"/>
            <button class="text-black text-xs border-[1px] border-black rounded-md p-4" onclick="searchByAuthor()">
                search
            </button>
        </div>

        <div>
            <label for="search_category" class="font-bold text-lg"> Search by Category : </label>
            <select id="search_category" class="border-b-[1px] p-2 px-6 border-slate-400 bg-white">
                {% for category in categories %}
                <option value="{{ category.title }}">{{ category.title }}</option>
                {% endfor %}
            </select>
            <button class="text-black text-xs border-[1px] border-black rounded-md p-4" onclick="searchByCategory()">
                search
            </button>
        </div>
    </div>

    {% for blog in blogs %}
    <div class="w-96 bg-slate-200 rounded-md border-[1px] border-black p-6">
        <div class="text-xl font-bold">{{ blog.title }}</div>
        <div>{{ blog.category.title }}</div>
        <div class="text-slate-600 text-sm">{{ blog.description }}</div>
        <div class="text-black text-xs">Creator : {{ blog.creator.full_name }}</div>
        <div class="mt-4">
            <button class="text-red-500 text-xs">DELETE</button>
        </div>
    </div>
    {% endfor %}

    <div class="flex gap-10">
        {% if blogs.has_previous %}
        <button class="text-blue-500" onclick="goPrev()"> <<< prev</button>
        {% endif %}
        {% if blogs.has_next %}
        <button class="text-blue-500" onclick="goNext()">next >>></button>
        {% endif %}
    </div>

</div>

{% endblock %}

admin/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}

<div class="h-full flex justify-center items-center gap-8">
    <div class="max-w-[700px] flex flex-col justify-center items-center gap-8">
        <div>
            <div>Total number of Blogs : {{ total_blogs_count }}</div>
            <div>Total number of Posts : {{ total_posts_count }}</div>
            <div>Total number of Categories : {{ total_categories_count }}</div>
        </div>

        <div>
            <canvas id="chartContainer" class=""></canvas>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <script>


            fetch("/admin/dashboard_data").then(
                (res) => res.json()
            ).then(
                (data)=>{

                    let category_blog_counts = [];
                    let category_titles = [];


                    for(let i=0; i<data.length; i++){
                        category_blog_counts.push(data[i].num_of_blogs);
                        category_titles.push(data[i].title);
                    }

                    const chart_data = {
                        datasets: [{
                            data: category_blog_counts
                        }],
                        labels: category_titles
                    };

                    const ctx = document.getElementById('chartContainer');

                    new Chart(ctx, {
                      type: 'pie',
                      data: chart_data,

                    });

                }
            );

        </script>
    </div>
</div>

{% endblock %}

admin/templates/login.html
<!-- login.html -->
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="/static/output.css">
    <title>Login</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
<div class="flex justify-center items-center h-screen">
    <div class="w-1/3">
        <h2 class="text-2xl mb-4">Login</h2>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" class="w-full p-2 border border-gray-300 rounded">
            <input type="password" name="password" placeholder="Password"
                   class="w-full p-2 border border-gray-300 rounded">
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded">Login</button>
        </form>
    </div>
</div>
</body>
</html>